package RTPS;


/**
* RTPS/ContentFilterProperty_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ContentFilterProperty_t implements org.omg.CORBA.portable.IDLEntity
{
  public String contentFilteredTopicName = null;
  public String relatedTopicName = null;
  public String filterClassName = null;
  public String filterExpression = null;
  public String expressionParameters[] = null;

  public ContentFilterProperty_t ()
  {
  } // ctor

  public ContentFilterProperty_t (String _contentFilteredTopicName, String _relatedTopicName, String _filterClassName, String _filterExpression, String[] _expressionParameters)
  {
    contentFilteredTopicName = _contentFilteredTopicName;
    relatedTopicName = _relatedTopicName;
    filterClassName = _filterClassName;
    filterExpression = _filterExpression;
    expressionParameters = _expressionParameters;
  } // ctor

} // class ContentFilterProperty_t
