package RTPS;


/**
* RTPS/ContentFilterProperty_tHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class ContentFilterProperty_tHelper
{
  private static String  _id = "IDL:RTPS/ContentFilterProperty_t:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.ContentFilterProperty_t that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.ContentFilterProperty_t extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (256);
          _members0[0] = new org.omg.CORBA.StructMember (
            "contentFilteredTopicName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (256);
          _members0[1] = new org.omg.CORBA.StructMember (
            "relatedTopicName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (256);
          _members0[2] = new org.omg.CORBA.StructMember (
            "filterClassName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "filterExpression",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "expressionParameters",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.ContentFilterProperty_tHelper.id (), "ContentFilterProperty_t", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.ContentFilterProperty_t read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.ContentFilterProperty_t value = new RTPS.ContentFilterProperty_t ();
    value.contentFilteredTopicName = istream.read_string ();
    if (value.contentFilteredTopicName.length () > (256))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.relatedTopicName = istream.read_string ();
    if (value.relatedTopicName.length () > (256))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.filterClassName = istream.read_string ();
    if (value.filterClassName.length () > (256))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value.filterExpression = istream.read_string ();
    int _len0 = istream.read_long ();
    value.expressionParameters = new String[_len0];
    for (int _o1 = 0;_o1 < value.expressionParameters.length; ++_o1)
      value.expressionParameters[_o1] = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.ContentFilterProperty_t value)
  {
    if (value.contentFilteredTopicName.length () > (256))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.contentFilteredTopicName);
    if (value.relatedTopicName.length () > (256))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.relatedTopicName);
    if (value.filterClassName.length () > (256))      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_string (value.filterClassName);
    ostream.write_string (value.filterExpression);
    ostream.write_long (value.expressionParameters.length);
    for (int _i0 = 0;_i0 < value.expressionParameters.length; ++_i0)
      ostream.write_string (value.expressionParameters[_i0]);
  }

}
