package RTPS;


/**
* RTPS/CountHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class CountHelper
{
  private static String  _id = "IDL:RTPS/Count:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.Count_t that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.Count_t extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = RTPS.Count_tHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.CountHelper.id (), "Count", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.Count_t read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.Count_t value = null;
    value = RTPS.Count_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.Count_t value)
  {
    RTPS.Count_tHelper.write (ostream, value);
  }

}
