package RTPS;

/**
* RTPS/Count_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Count_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.Count_t value = null;

  public Count_tHolder ()
  {
  }

  public Count_tHolder (RTPS.Count_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.Count_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.Count_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.Count_tHelper.type ();
  }

}
