package RTPS;

/**
* RTPS/DiscoveredTopicDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class DiscoveredTopicDataHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.DiscoveredTopicData value = null;

  public DiscoveredTopicDataHolder ()
  {
  }

  public DiscoveredTopicDataHolder (RTPS.DiscoveredTopicData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.DiscoveredTopicDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.DiscoveredTopicDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.DiscoveredTopicDataHelper.type ();
  }

}
