package RTPS;


/**
* RTPS/DiscoveredReaderData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class DiscoveredReaderData implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.SubscriptionBuiltinTopicData ddsSubscriptionData = null;
  public RTPS.ReaderProxy readerProxy = null;
  public RTPS.ContentFilterProperty_t contentFilterProperty = null;

  public DiscoveredReaderData ()
  {
  } // ctor

  public DiscoveredReaderData (DDS.SubscriptionBuiltinTopicData _ddsSubscriptionData, RTPS.ReaderProxy _readerProxy, RTPS.ContentFilterProperty_t _contentFilterProperty)
  {
    ddsSubscriptionData = _ddsSubscriptionData;
    readerProxy = _readerProxy;
    contentFilterProperty = _contentFilterProperty;
  } // ctor

} // class DiscoveredReaderData
