package RTPS;


/**
* RTPS/DiscoveredTopicDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class DiscoveredTopicDataHelper
{
  private static String  _id = "IDL:RTPS/DiscoveredTopicData:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.DiscoveredTopicData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.DiscoveredTopicData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = DDS.TopicBuiltinTopicDataHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "ddsTopicData",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.DiscoveredTopicDataHelper.id (), "DiscoveredTopicData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.DiscoveredTopicData read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.DiscoveredTopicData value = new RTPS.DiscoveredTopicData ();
    value.ddsTopicData = DDS.TopicBuiltinTopicDataHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.DiscoveredTopicData value)
  {
    DDS.TopicBuiltinTopicDataHelper.write (ostream, value.ddsTopicData);
  }

}
