package RTPS;

/**
* RTPS/DiscoveredWriterDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class DiscoveredWriterDataHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.DiscoveredWriterData value = null;

  public DiscoveredWriterDataHolder ()
  {
  }

  public DiscoveredWriterDataHolder (RTPS.DiscoveredWriterData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.DiscoveredWriterDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.DiscoveredWriterDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.DiscoveredWriterDataHelper.type ();
  }

}
