package RTPS;

/**
* RTPS/DiscoveredReaderDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class DiscoveredReaderDataHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.DiscoveredReaderData value = null;

  public DiscoveredReaderDataHolder ()
  {
  }

  public DiscoveredReaderDataHolder (RTPS.DiscoveredReaderData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.DiscoveredReaderDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.DiscoveredReaderDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.DiscoveredReaderDataHelper.type ();
  }

}
