package RTPS;


/**
* RTPS/DiscoveredWriterData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class DiscoveredWriterData implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.PublicationBuiltinTopicData ddsPublicationData = null;
  public RTPS.WriterProxy writerProxy = null;

  public DiscoveredWriterData ()
  {
  } // ctor

  public DiscoveredWriterData (DDS.PublicationBuiltinTopicData _ddsPublicationData, RTPS.WriterProxy _writerProxy)
  {
    ddsPublicationData = _ddsPublicationData;
    writerProxy = _writerProxy;
  } // ctor

} // class DiscoveredWriterData
