package RTPS;


/**
* RTPS/DiscoveredWriterDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class DiscoveredWriterDataHelper
{
  private static String  _id = "IDL:RTPS/DiscoveredWriterData:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.DiscoveredWriterData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.DiscoveredWriterData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = DDS.PublicationBuiltinTopicDataHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "ddsPublicationData",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.WriterProxyHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "writerProxy",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.DiscoveredWriterDataHelper.id (), "DiscoveredWriterData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.DiscoveredWriterData read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.DiscoveredWriterData value = new RTPS.DiscoveredWriterData ();
    value.ddsPublicationData = DDS.PublicationBuiltinTopicDataHelper.read (istream);
    value.writerProxy = RTPS.WriterProxyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.DiscoveredWriterData value)
  {
    DDS.PublicationBuiltinTopicDataHelper.write (ostream, value.ddsPublicationData);
    RTPS.WriterProxyHelper.write (ostream, value.writerProxy);
  }

}
