package RTPS;


/**
* RTPS/DiscoveredReaderDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class DiscoveredReaderDataHelper
{
  private static String  _id = "IDL:RTPS/DiscoveredReaderData:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.DiscoveredReaderData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.DiscoveredReaderData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = DDS.SubscriptionBuiltinTopicDataHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "ddsSubscriptionData",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.ReaderProxyHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "readerProxy",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.ContentFilterProperty_tHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "contentFilterProperty",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.DiscoveredReaderDataHelper.id (), "DiscoveredReaderData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.DiscoveredReaderData read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.DiscoveredReaderData value = new RTPS.DiscoveredReaderData ();
    value.ddsSubscriptionData = DDS.SubscriptionBuiltinTopicDataHelper.read (istream);
    value.readerProxy = RTPS.ReaderProxyHelper.read (istream);
    value.contentFilterProperty = RTPS.ContentFilterProperty_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.DiscoveredReaderData value)
  {
    DDS.SubscriptionBuiltinTopicDataHelper.write (ostream, value.ddsSubscriptionData);
    RTPS.ReaderProxyHelper.write (ostream, value.readerProxy);
    RTPS.ContentFilterProperty_tHelper.write (ostream, value.contentFilterProperty);
  }

}
