package RTPS;

/**
* RTPS/EntityName_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class EntityName_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.EntityName_t value = null;

  public EntityName_tHolder ()
  {
  }

  public EntityName_tHolder (RTPS.EntityName_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.EntityName_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.EntityName_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.EntityName_tHelper.type ();
  }

}
