package RTPS;


/**
* RTPS/EntityName_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class EntityName_t implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  public EntityName_t ()
  {
  } // ctor

  public EntityName_t (String _name)
  {
    name = _name;
  } // ctor

} // class EntityName_t
