package RTPS;


/**
* RTPS/EntityId_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class EntityId_t implements org.omg.CORBA.portable.IDLEntity
{
  public byte entityKey[] = null;
  public byte entityKind = (byte)0;

  public EntityId_t ()
  {
  } // ctor

  public EntityId_t (byte[] _entityKey, byte _entityKind)
  {
    entityKey = _entityKey;
    entityKind = _entityKind;
  } // ctor

} // class EntityId_t
