package RTPS;


/**
* RTPS/FragmentNumber_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class FragmentNumber_t implements org.omg.CORBA.portable.IDLEntity
{
  public int value = (int)0;

  public FragmentNumber_t ()
  {
  } // ctor

  public FragmentNumber_t (int _value)
  {
    value = _value;
  } // ctor

} // class FragmentNumber_t
