package RTPS;


/**
* RTPS/FragmentNumberSet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class FragmentNumberSet implements org.omg.CORBA.portable.IDLEntity
{
  public RTPS.FragmentNumber_t bitmapBase = null;
  public int bitmap[] = null;

  public FragmentNumberSet ()
  {
  } // ctor

  public FragmentNumberSet (RTPS.FragmentNumber_t _bitmapBase, int[] _bitmap)
  {
    bitmapBase = _bitmapBase;
    bitmap = _bitmap;
  } // ctor

} // class FragmentNumberSet
