package RTPS;

/**
* RTPS/FragmentNumberSetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class FragmentNumberSetHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.FragmentNumberSet value = null;

  public FragmentNumberSetHolder ()
  {
  }

  public FragmentNumberSetHolder (RTPS.FragmentNumberSet initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.FragmentNumberSetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.FragmentNumberSetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.FragmentNumberSetHelper.type ();
  }

}
