package RTPS;


/**
* RTPS/GuidPrefixHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class GuidPrefixHelper
{
  private static String  _id = "IDL:RTPS/GuidPrefix:1.0";

  public static void insert (org.omg.CORBA.Any a, byte[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static byte[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (12, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.GuidPrefix_tHelper.id (), "GuidPrefix_t", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.GuidPrefixHelper.id (), "GuidPrefix", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static byte[] read (org.omg.CORBA.portable.InputStream istream)
  {
    byte value[] = null;
    value = RTPS.GuidPrefix_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, byte[] value)
  {
    RTPS.GuidPrefix_tHelper.write (ostream, value);
  }

}
