package RTPS;


/**
* RTPS/GUID_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class GUID_t implements org.omg.CORBA.portable.IDLEntity
{
  public byte guidPrefix[] = null;
  public RTPS.EntityId_t entityId = null;

  public GUID_t ()
  {
  } // ctor

  public GUID_t (byte[] _guidPrefix, RTPS.EntityId_t _entityId)
  {
    guidPrefix = _guidPrefix;
    entityId = _entityId;
  } // ctor

} // class GUID_t
