package RTPS;

/**
* RTPS/GUID_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class GUID_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.GUID_t value = null;

  public GUID_tHolder ()
  {
  }

  public GUID_tHolder (RTPS.GUID_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.GUID_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.GUID_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.GUID_tHelper.type ();
  }

}
