package RTPS;


/**
* RTPS/GUID_tHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class GUID_tHelper
{
  private static String  _id = "IDL:RTPS/GUID_t:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.GUID_t that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.GUID_t extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (12, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.GuidPrefix_tHelper.id (), "GuidPrefix_t", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "guidPrefix",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.EntityId_tHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "entityId",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.GUID_tHelper.id (), "GUID_t", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.GUID_t read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.GUID_t value = new RTPS.GUID_t ();
    value.guidPrefix = RTPS.GuidPrefix_tHelper.read (istream);
    value.entityId = RTPS.EntityId_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.GUID_t value)
  {
    RTPS.GuidPrefix_tHelper.write (ostream, value.guidPrefix);
    RTPS.EntityId_tHelper.write (ostream, value.entityId);
  }

}
