package RTPS;


/**
* RTPS/KeyHash_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class KeyHash_t implements org.omg.CORBA.portable.IDLEntity
{
  public byte value[] = null;

  public KeyHash_t ()
  {
  } // ctor

  public KeyHash_t (byte[] _value)
  {
    value = _value;
  } // ctor

} // class KeyHash_t
