package RTPS;


/**
* RTPS/LocatorListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class LocatorListHelper
{
  private static String  _id = "IDL:RTPS/LocatorList:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.Locator_t[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.Locator_t[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = RTPS.Locator_tHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (8, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.LocatorListHelper.id (), "LocatorList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.Locator_t[] read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.Locator_t value[] = null;
    int _len0 = istream.read_long ();
    if (_len0 > (8))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    value = new RTPS.Locator_t[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = RTPS.Locator_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.Locator_t[] value)
  {
    if (value.length > (8))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      RTPS.Locator_tHelper.write (ostream, value[_i0]);
  }

}
