package RTPS;

/**
* RTPS/Locator_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Locator_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.Locator_t value = null;

  public Locator_tHolder ()
  {
  }

  public Locator_tHolder (RTPS.Locator_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.Locator_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.Locator_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.Locator_tHelper.type ();
  }

}
