package RTPS;


/**
* RTPS/LocatorUDPv4_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class LocatorUDPv4_t implements org.omg.CORBA.portable.IDLEntity
{
  public int address = (int)0;
  public int port = (int)0;

  public LocatorUDPv4_t ()
  {
  } // ctor

  public LocatorUDPv4_t (int _address, int _port)
  {
    address = _address;
    port = _port;
  } // ctor

} // class LocatorUDPv4_t
