package RTPS;


/**
* RTPS/Locator_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Locator_t implements org.omg.CORBA.portable.IDLEntity
{
  public int kind = (int)0;
  public int port = (int)0;
  public byte address[] = null;

  public Locator_t ()
  {
  } // ctor

  public Locator_t (int _kind, int _port, byte[] _address)
  {
    kind = _kind;
    port = _port;
    address = _address;
  } // ctor

} // class Locator_t
