package RTPS;

/**
* RTPS/LocatorUDPv4_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class LocatorUDPv4_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.LocatorUDPv4_t value = null;

  public LocatorUDPv4_tHolder ()
  {
  }

  public LocatorUDPv4_tHolder (RTPS.LocatorUDPv4_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.LocatorUDPv4_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.LocatorUDPv4_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.LocatorUDPv4_tHelper.type ();
  }

}
