package RTPS;


/**
* RTPS/LocatorListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class LocatorListHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.Locator_t value[] = null;

  public LocatorListHolder ()
  {
  }

  public LocatorListHolder (RTPS.Locator_t[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.LocatorListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.LocatorListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.LocatorListHelper.type ();
  }

}
