package RTPS;


/**
* RTPS/Parameter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Parameter implements org.omg.CORBA.portable.IDLEntity
{
  public short parameterId = (short)0;
  public short length = (short)0;
  public byte value[] = null;

  public Parameter ()
  {
  } // ctor

  public Parameter (short _parameterId, short _length, byte[] _value)
  {
    parameterId = _parameterId;
    length = _length;
    value = _value;
  } // ctor

} // class Parameter
