package RTPS;


/**
* RTPS/ParticipantProxyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class ParticipantProxyHelper
{
  private static String  _id = "IDL:RTPS/ParticipantProxy:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.ParticipantProxy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.ParticipantProxy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = RTPS.ProtocolVersion_tHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "protocolVersion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (12, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.GuidPrefix_tHelper.id (), "GuidPrefix_t", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "guidPrefix",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.VendorId_tHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "vendorId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "expectsInlineQos",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.ParticipantProxyHelper.id (), "ParticipantProxy", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.ParticipantProxy read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.ParticipantProxy value = new RTPS.ParticipantProxy ();
    value.protocolVersion = RTPS.ProtocolVersion_tHelper.read (istream);
    value.guidPrefix = RTPS.GuidPrefix_tHelper.read (istream);
    value.vendorId = RTPS.VendorId_tHelper.read (istream);
    value.expectsInlineQos = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.ParticipantProxy value)
  {
    RTPS.ProtocolVersion_tHelper.write (ostream, value.protocolVersion);
    RTPS.GuidPrefix_tHelper.write (ostream, value.guidPrefix);
    RTPS.VendorId_tHelper.write (ostream, value.vendorId);
    ostream.write_boolean (value.expectsInlineQos);
  }

}
