package RTPS;

/**
* RTPS/ParticipantMessageDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ParticipantMessageDataHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.ParticipantMessageData value = null;

  public ParticipantMessageDataHolder ()
  {
  }

  public ParticipantMessageDataHolder (RTPS.ParticipantMessageData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.ParticipantMessageDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.ParticipantMessageDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.ParticipantMessageDataHelper.type ();
  }

}
