package RTPS;


/**
* RTPS/ParticipantMessageDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class ParticipantMessageDataHelper
{
  private static String  _id = "IDL:RTPS/ParticipantMessageData:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.ParticipantMessageData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.ParticipantMessageData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (12, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.GuidPrefix_tHelper.id (), "GuidPrefix_t", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "participantGuidPrefix",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (4, _tcOf_members0 );
          _members0[1] = new org.omg.CORBA.StructMember (
            "kind",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "data",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.ParticipantMessageDataHelper.id (), "ParticipantMessageData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.ParticipantMessageData read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.ParticipantMessageData value = new RTPS.ParticipantMessageData ();
    value.participantGuidPrefix = RTPS.GuidPrefix_tHelper.read (istream);
    value.kind = new byte[4];
    for (int _o0 = 0;_o0 < (4); ++_o0)
    {
      value.kind[_o0] = istream.read_octet ();
    }
    int _len1 = istream.read_long ();
    value.data = new byte[_len1];
    istream.read_octet_array (value.data, 0, _len1);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.ParticipantMessageData value)
  {
    RTPS.GuidPrefix_tHelper.write (ostream, value.participantGuidPrefix);
    if (value.kind.length != (4))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (4); ++_i0)
    {
      ostream.write_octet (value.kind[_i0]);
    }
    ostream.write_long (value.data.length);
    ostream.write_octet_array (value.data, 0, value.data.length);
  }

}
