package RTPS;


/**
* RTPS/ParticipantProxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ParticipantProxy implements org.omg.CORBA.portable.IDLEntity
{
  public RTPS.ProtocolVersion_t protocolVersion = null;
  public byte guidPrefix[] = null;
  public RTPS.VendorId_t vendorId = null;
  public boolean expectsInlineQos = false;

  public ParticipantProxy ()
  {
  } // ctor

  public ParticipantProxy (RTPS.ProtocolVersion_t _protocolVersion, byte[] _guidPrefix, RTPS.VendorId_t _vendorId, boolean _expectsInlineQos)
  {
    protocolVersion = _protocolVersion;
    guidPrefix = _guidPrefix;
    vendorId = _vendorId;
    expectsInlineQos = _expectsInlineQos;
  } // ctor

} // class ParticipantProxy
