package RTPS;

/**
* RTPS/ParticipantProxyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ParticipantProxyHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.ParticipantProxy value = null;

  public ParticipantProxyHolder ()
  {
  }

  public ParticipantProxyHolder (RTPS.ParticipantProxy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.ParticipantProxyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.ParticipantProxyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.ParticipantProxyHelper.type ();
  }

}
