package RTPS;

/**
* RTPS/Property_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Property_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.Property_t value = null;

  public Property_tHolder ()
  {
  }

  public Property_tHolder (RTPS.Property_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.Property_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.Property_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.Property_tHelper.type ();
  }

}
