package RTPS;


/**
* RTPS/Property_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Property_t implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String value = null;

  public Property_t ()
  {
  } // ctor

  public Property_t (String _name, String _value)
  {
    name = _name;
    value = _value;
  } // ctor

} // class Property_t
