package RTPS;


/**
* RTPS/ProtocolVersion_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ProtocolVersion_t implements org.omg.CORBA.portable.IDLEntity
{
  public byte major = (byte)0;
  public byte minor = (byte)0;

  public ProtocolVersion_t ()
  {
  } // ctor

  public ProtocolVersion_t (byte _major, byte _minor)
  {
    major = _major;
    minor = _minor;
  } // ctor

} // class ProtocolVersion_t
