package RTPS;

/**
* RTPS/ProtocolVersion_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ProtocolVersion_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.ProtocolVersion_t value = null;

  public ProtocolVersion_tHolder ()
  {
  }

  public ProtocolVersion_tHolder (RTPS.ProtocolVersion_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.ProtocolVersion_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.ProtocolVersion_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.ProtocolVersion_tHelper.type ();
  }

}
