package RTPS;


/**
* RTPS/ProtocolVersionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class ProtocolVersionHelper
{
  private static String  _id = "IDL:RTPS/ProtocolVersion:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.ProtocolVersion_t that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.ProtocolVersion_t extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = RTPS.ProtocolVersion_tHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (RTPS.ProtocolVersionHelper.id (), "ProtocolVersion", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.ProtocolVersion_t read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.ProtocolVersion_t value = null;
    value = RTPS.ProtocolVersion_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.ProtocolVersion_t value)
  {
    RTPS.ProtocolVersion_tHelper.write (ostream, value);
  }

}
