package RTPS;

/**
* RTPS/ReliabilityKind_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class ReliabilityKind_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.ReliabilityKind_t value = null;

  public ReliabilityKind_tHolder ()
  {
  }

  public ReliabilityKind_tHolder (RTPS.ReliabilityKind_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.ReliabilityKind_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.ReliabilityKind_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.ReliabilityKind_tHelper.type ();
  }

}
