package RTPS;


/**
* RTPS/SequenceNumberSet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SequenceNumberSet implements org.omg.CORBA.portable.IDLEntity
{
  public RTPS.SequenceNumber_t bitmapBase = null;
  public int bitmap[] = null;

  public SequenceNumberSet ()
  {
  } // ctor

  public SequenceNumberSet (RTPS.SequenceNumber_t _bitmapBase, int[] _bitmap)
  {
    bitmapBase = _bitmapBase;
    bitmap = _bitmap;
  } // ctor

} // class SequenceNumberSet
