package RTPS;

/**
* RTPS/SequenceNumber_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SequenceNumber_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.SequenceNumber_t value = null;

  public SequenceNumber_tHolder ()
  {
  }

  public SequenceNumber_tHolder (RTPS.SequenceNumber_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.SequenceNumber_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.SequenceNumber_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.SequenceNumber_tHelper.type ();
  }

}
