package RTPS;


/**
* RTPS/SequenceNumber_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SequenceNumber_t implements org.omg.CORBA.portable.IDLEntity
{
  public int high = (int)0;
  public int low = (int)0;

  public SequenceNumber_t ()
  {
  } // ctor

  public SequenceNumber_t (int _high, int _low)
  {
    high = _high;
    low = _low;
  } // ctor

} // class SequenceNumber_t
