package RTPS;

/**
* RTPS/SPDPdiscoveredParticipantDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SPDPdiscoveredParticipantDataHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.SPDPdiscoveredParticipantData value = null;

  public SPDPdiscoveredParticipantDataHolder ()
  {
  }

  public SPDPdiscoveredParticipantDataHolder (RTPS.SPDPdiscoveredParticipantData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.SPDPdiscoveredParticipantDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.SPDPdiscoveredParticipantDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.SPDPdiscoveredParticipantDataHelper.type ();
  }

}
