package RTPS;


/**
* RTPS/SPDPdiscoveredParticipantData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SPDPdiscoveredParticipantData implements org.omg.CORBA.portable.IDLEntity
{
  public DDS.ParticipantBuiltinTopicData ddsParticipantData = null;
  public RTPS.ParticipantProxy participantProxy = null;
  public DDS.Duration_t leaseDuration = null;

  public SPDPdiscoveredParticipantData ()
  {
  } // ctor

  public SPDPdiscoveredParticipantData (DDS.ParticipantBuiltinTopicData _ddsParticipantData, RTPS.ParticipantProxy _participantProxy, DDS.Duration_t _leaseDuration)
  {
    ddsParticipantData = _ddsParticipantData;
    participantProxy = _participantProxy;
    leaseDuration = _leaseDuration;
  } // ctor

} // class SPDPdiscoveredParticipantData
