package RTPS;


/**
* RTPS/StatusInfo_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class StatusInfo_t implements org.omg.CORBA.portable.IDLEntity
{
  public byte value[] = null;

  public StatusInfo_t ()
  {
  } // ctor

  public StatusInfo_t (byte[] _value)
  {
    value = _value;
  } // ctor

} // class StatusInfo_t
