package RTPS;


/**
* RTPS/SubmessageHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SubmessageHeader implements org.omg.CORBA.portable.IDLEntity
{
  public byte submessageId = (byte)0;
  public byte flags = (byte)0;
  public short submessageLength = (short)0;

  public SubmessageHeader ()
  {
  } // ctor

  public SubmessageHeader (byte _submessageId, byte _flags, short _submessageLength)
  {
    submessageId = _submessageId;
    flags = _flags;
    submessageLength = _submessageLength;
  } // ctor

} // class SubmessageHeader
