package RTPS;

/**
* RTPS/SubmessageHeaderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class SubmessageHeaderHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.SubmessageHeader value = null;

  public SubmessageHeaderHolder ()
  {
  }

  public SubmessageHeaderHolder (RTPS.SubmessageHeader initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.SubmessageHeaderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.SubmessageHeaderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.SubmessageHeaderHelper.type ();
  }

}
