package RTPS;

/**
* RTPS/Time_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Time_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.Time_t value = null;

  public Time_tHolder ()
  {
  }

  public Time_tHolder (RTPS.Time_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.Time_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.Time_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.Time_tHelper.type ();
  }

}
