package RTPS;


/**
* RTPS/Time_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class Time_t implements org.omg.CORBA.portable.IDLEntity
{
  public int seconds = (int)0;

  // time in seconds
  public int fraction = (int)0;

  public Time_t ()
  {
  } // ctor

  public Time_t (int _seconds, int _fraction)
  {
    seconds = _seconds;
    fraction = _fraction;
  } // ctor

} // class Time_t
