package RTPS;

/**
* RTPS/TopicKind_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class TopicKind_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.TopicKind_t value = null;

  public TopicKind_tHolder ()
  {
  }

  public TopicKind_tHolder (RTPS.TopicKind_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.TopicKind_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.TopicKind_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.TopicKind_tHelper.type ();
  }

}
