package RTPS;


/**
* RTPS/VendorId_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class VendorId_t implements org.omg.CORBA.portable.IDLEntity
{
  public byte vendorId[] = null;

  public VendorId_t ()
  {
  } // ctor

  public VendorId_t (byte[] _vendorId)
  {
    vendorId = _vendorId;
  } // ctor

} // class VendorId_t
