package RTPS;

/**
* RTPS/VendorId_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class VendorId_tHolder implements org.omg.CORBA.portable.Streamable
{
  public RTPS.VendorId_t value = null;

  public VendorId_tHolder ()
  {
  }

  public VendorId_tHolder (RTPS.VendorId_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTPS.VendorId_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTPS.VendorId_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTPS.VendorId_tHelper.type ();
  }

}
