package RTPS;


/**
* RTPS/WriterProxyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

abstract public class WriterProxyHelper
{
  private static String  _id = "IDL:RTPS/WriterProxy:1.0";

  public static void insert (org.omg.CORBA.Any a, RTPS.WriterProxy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTPS.WriterProxy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = RTPS.GUID_tHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "remoteWriterGuid",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.Locator_tHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "unicastLocatorList",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTPS.Locator_tHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "multicastLocatorList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTPS.WriterProxyHelper.id (), "WriterProxy", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTPS.WriterProxy read (org.omg.CORBA.portable.InputStream istream)
  {
    RTPS.WriterProxy value = new RTPS.WriterProxy ();
    value.remoteWriterGuid = RTPS.GUID_tHelper.read (istream);
    int _len0 = istream.read_long ();
    value.unicastLocatorList = new RTPS.Locator_t[_len0];
    for (int _o1 = 0;_o1 < value.unicastLocatorList.length; ++_o1)
      value.unicastLocatorList[_o1] = RTPS.Locator_tHelper.read (istream);
    int _len1 = istream.read_long ();
    value.multicastLocatorList = new RTPS.Locator_t[_len1];
    for (int _o2 = 0;_o2 < value.multicastLocatorList.length; ++_o2)
      value.multicastLocatorList[_o2] = RTPS.Locator_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTPS.WriterProxy value)
  {
    RTPS.GUID_tHelper.write (ostream, value.remoteWriterGuid);
    ostream.write_long (value.unicastLocatorList.length);
    for (int _i0 = 0;_i0 < value.unicastLocatorList.length; ++_i0)
      RTPS.Locator_tHelper.write (ostream, value.unicastLocatorList[_i0]);
    ostream.write_long (value.multicastLocatorList.length);
    for (int _i1 = 0;_i1 < value.multicastLocatorList.length; ++_i1)
      RTPS.Locator_tHelper.write (ostream, value.multicastLocatorList[_i1]);
  }

}
