package RTPS;


/**
* RTPS/WriterProxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rtps.idl
* 8. helmikuuta 2012 9.16.40 EET
*/

public final class WriterProxy implements org.omg.CORBA.portable.IDLEntity
{
  public RTPS.GUID_t remoteWriterGuid = null;
  public RTPS.Locator_t unicastLocatorList[] = null;
  public RTPS.Locator_t multicastLocatorList[] = null;

  public WriterProxy ()
  {
  } // ctor

  public WriterProxy (RTPS.GUID_t _remoteWriterGuid, RTPS.Locator_t[] _unicastLocatorList, RTPS.Locator_t[] _multicastLocatorList)
  {
    remoteWriterGuid = _remoteWriterGuid;
    unicastLocatorList = _unicastLocatorList;
    multicastLocatorList = _multicastLocatorList;
  } // ctor

} // class WriterProxy
